# Generated by Django 3.0.8 on 2020-07-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vlans',
            fields=[
                ('vlan_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('vlan_name', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
